name: '[builder] CI for release'

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:buildkit
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses:  docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push master
        if: contains(github.ref, 'refs/heads')
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            disaster/dfp-api:master
      - name: Build and push release
        if: contains(github.ref, 'refs/tags')
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v8
          push: true
          tags: |
            disaster/dfp-ui:${GITHUB_REF#refs/tags/}
      